# Generated by Django 3.1.5 on 2021-01-26 18:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=18, max_digits=100)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=100)),
                ('type', models.CharField(choices=[('ETH', 'ethereum'), ('BTC', 'bitcoin')], max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
